
[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "~0.6.0"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "~0.6.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "~1.13.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.12.10"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "~1.20.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.30.3"
